version: '3'

services:
  rev-proxy:
    volumes:
      - "./html/nginx.html:/var/www/html/index.html"
    depends_on:
      - gblog
    env_file:
      - "./nginx/.env"

  moodlephp:
    build:
      context: "./moodle"
      dockerfile: "Dockerfile.dev"
    volumes:
      - "./moodle/phpinfo.php:/var/www/html/phpinfo.php"
      - "./html/3.html:/var/www/testing/index.html"
      - "./html/2.html:/var/www/testin/index.html"
      - "~/.vimrc.base:/root/.vimrc"
    env_file:
      - "./moodle/.env"

  gblog:
    image: ghost
    ports:
      - 2368
    environment:
      - NODE_ENV=development
    networks:
      - colasloth
    container_name: gblog
