version: '3'

services:
  rev-proxy:
    image: nginx
    volumes:
      - "./nginx/conf.d/moodle.conf:/etc/nginx/templates/default.conf.template"
    ports:
      - "80:80"
    depends_on:
      - moodlephp
      - moodledb
    networks:
      - colasloth
    container_name: rev-proxy

  moodledb:
    image: mysql 
    environment:
      - MYSQL_DATABASE=moodledb
      - MYSQL_USER=moodledbuser
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3306
    networks:
      - colasloth
    container_name: moodledb

  moodlephp:
    image: moodle
    build:
      context: "./moodle/"
    ports:
      - 80
    volumes:
      - "./moodle/colasloth.com.conf:/etc/apache2/sites-enabled/colasloth.com.conf"
      - "./moodle/php.ini:/usr/local/etc/php/php.ini"
      - "./moodle/moodle:/var/www/moodle:rw"
      - "./html/1.html:/var/www/testing/index.html"
    depends_on:
      - moodledb
    networks:
      - colasloth
    container_name: moodlephp

    # web:
    #   image: odoo
    #   depends_on:
    #     - db
    #   ports:
    #     - 8069
    #   networks:
    #     - colasloth
    #   container_name: odoo_project

    # db:
    #   image: postgres:13
    #   environment:
    #     - POSTGRES_DB=postgres
    #     - POSTGRES_PASSWORD=odoo
    #     - POSTGRES_USER=odoo
    #   networks:
    #     - colasloth
    #   container_name: odoodb

networks:
  colasloth:
