version: '3'

services:
  rev-proxy:
    image: nginx
    volumes:
      - "./nginx/conf.d/moodle.conf:/etc/nginx/templates/default.conf.template"
    ports:
      - "80:80"
    env_file:
      - "./nginx/.env"
    depends_on:
      - moodlephp
      - moodledb
      - gblog
    networks:
      - colasloth
    container_name: rev-proxy

  moodledb:
    image: mysql 
    environment:
      - MYSQL_DATABASE=moodledb
      - MYSQL_USER=moodledbuser
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3306
    networks:
      - colasloth
    container_name: moodledb

  moodlephp:
    image: moodle
    build:
      context: "./moodle/"
    ports:
      - 80
    volumes:
      - "./moodle/colasloth.com.conf:/etc/apache2/sites-enabled/colasloth.com.conf"
      - "./moodle/phpinfo.php:/var/www/html/phpinfo.php"
      - "./moodle/php.ini:/usr/local/etc/php/php.ini"
      - "./html/1.html:/var/www/testing/index.html"
      - "./html/2.html:/var/www/testin/index.html"
      - "./html/3.html:/var/www/html/index.html"
      - "./moodle/moodle:/var/www/moodle:rw"
    env_file:
      - "./moodle/.env"
    depends_on:
      - moodledb
    networks:
      - colasloth
    container_name: moodlephp

  gblog:
    image: ghost
    ports:
      - 2368
    environment:
      - NODE_ENV=development
    networks:
      - colasloth
    container_name: gblog
    
    # web:
    #   image: odoo
    #   depends_on:
    #     - db
    #   ports:
    #     - 8069
    #   networks:
    #     - colasloth
    #   container_name: odoo_project

    # db:
    #   image: postgres:13
    #   environment:
    #     - POSTGRES_DB=postgres
    #     - POSTGRES_PASSWORD=odoo
    #     - POSTGRES_USER=odoo
    #   networks:
    #     - colasloth
    #   container_name: odoodb

networks:
  colasloth:
