FROM php:8.1-apache
LABEL maintainer="Cabbar Serif <cabbar.serif@hotmail.com>"

## Dependencies for moodle
RUN apt-get update &&\ 
    apt-get install -y libzip-dev libpng-dev libicu-dev libxml2-dev &&\
    docker-php-ext-install mysqli pdo_mysql gd intl zip soap opcache exif

RUN mkdir -p /var/www/moodledata &&\
    chown -R www-data:www-data /var/www/

RUN apt-get install -y vim

COPY ./moodle.colasloth.com.conf /etc/apache2/sites-enabled/colasloth.com.conf

EXPOSE 80

ENTRYPOINT ["docker-php-entrypoint"]

CMD ["apache2-foreground"]
